export default {
    ADD: 'ADD_ACCOUNT',
    REMOVE: 'REMOVE_ACCOUNT',
    RESET: 'RESET_ACCOUNT',
    UPDATE: 'UPDATE_ACCOUNT',
    GET: 'GET_ACCOUNT',
    GETACTIVEACCOUNT: 'GET_ACTIVE_ACCOUNT',
    SETACCTIVEACCOUNT: 'SET_ACTIVE_ACCOUNT'
  };
  